version: 2.1

executors:
  default:
    docker:
      - image: circleci/python:latest
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: password

jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          command: poetry config virtualenvs.create false
          name: Disable Poetry virtualenvs creating
      - run:
          command: poetry install
          name: Install dependencies
  test:
    executor: default
    steps:
      - run:
          command: pytest --cov
          name: Test

workflows:
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
