# Generated by Django 3.0.2 on 2020-03-13 20:50

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_resized_thumbnail_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[960, 540], upload_to='photos/%Y/%m/%d'),
        ),
    ]
