# Generated by Django 3.0.2 on 2020-03-14 20:51

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_do_not_crop_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='post',
            name='image_showing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, size=[960, 540], upload_to='photos/%Y/%m/%d'),
        ),
    ]
