# Generated by Django 3.0.2 on 2020-03-15 19:51

from django.db import migrations

from blog.utils import unique_slugify


def populate_slugs(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    Category = apps.get_model('blog', 'Category')
    for post in Post.objects.all().order_by('id'):
        post.slug = unique_slugify(Post, post.title)
        post.save()
    for category in Category.objects.all().order_by('id'):
        category.slug = unique_slugify(Category, category.name)
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_category_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
    ]
